### ISSUE TITLE
3. Learning the GraphQL Workflow/Adding Queries To Schema

### ISSUE THREAD

**Issue by schickling** [graphcool/docs#19]
> This issue was moved originally created by @aarmand here: https://github.com/graphcool/dashboard/issues/213

How are we copy and pasting this into our code exactly? Is there a way to download the project after we have added Models and fields? 

Also, when I right a new query that I want to use in the playground, it would make sense to have an option to "add query to schema". With your current set up, per the Guide instructions, I copy/paste'd the new query i wanted to use into VSCODE. I had to look for the schema const's because there was no schema file. There might be some reason why you shouldnt do this that I am missing. But the following workflow would be useful. Write a new query, select add to schema if you want to use it, its added to our graphql schema, staging/prod(whatever), version of app schema is updated. Then have a button somewhere to do an update to your local dev code. Or the person can go do a sync via git. 

![graphcool3](https://cloud.githubusercontent.com/assets/2370391/18785342/f9b0316e-8197-11e6-87d2-1e171711f8d3.PNG)

**Comment by schickling** [comment]
@marktani do you want to take a look at this?

**Comment by marktani** [comment]
@aarmand you seem to have gotten the impression from the guide that you have to add queries to your schema before you can use them. That is a misconception. All queries and mutations that you can use at Graphcool are automatically generated based on your models and relations .

The guide suggests that you *explore* the available queries (rather than create them) in the playground before you use them in your GraphQL client. I'll leave this issue open so I can reword the relevant paragraph to better emphatize this meaning.

> How are we copy and pasting this into our code exactly? 

The  "copy & paste" step is highly depending on the GraphQL client you are using. See examples below to get an idea how that works.

> Is there a way to download the project after we have added Models and fields?

During the getting started tour at the beginning, you have the possibility to download different Angular or React Instagram clone projects that work nicely together with the models from the getting started tour and already use your project endpoint, so you are ready to go! Have a look at their source code to help you setting up a frontend app that fits to your project:

* [Angular and Apollo](https://github.com/graphcool-examples/angular-apollo-instagram-example)
* [React and Apollo](https://github.com/graphcool-examples/react-apollo-instagram-example)
* [React and Relay](https://github.com/graphcool-examples/react-relay-instagram-example)

**Comment by aarmand** [comment]
For reference, the language we are talking about is here: [https://docs.graph.cool/guides/setting-up-a-graphql-backend-in-5-minutes](url). It reads "When building an app with GraphQL the best workflow is usually to first write the query in the playground and then "copy & paste" it into your code". Im doing this on the react-apollo example.

I did in fact get the impression from the language that I was to copy and paste into my project code. In fact, we are writing the query in graphiql, so when it then says, copy to your code, it wouldn't make sense that you are pasting in the same place you just copied from. Still wouldn't know what to do here. Since graph.cool is automatically generating the queries in the code why would I go into it and paste it? I'm clearly missing something here.

Regarding downloading the project AFTER I have added queries to my, is there a place to do that?

How can I inspect the schema code created with graph.cool as shown in this example in apollostack dev docs [here](http://dev-home.apollodata.com/) ?

**Comment by marktani** [comment]
So first of all, I agree that the language in the guide is misleading and I'm going to fix that in the coming days, sorry for your troubles!

> Regarding downloading the project AFTER I have added queries to my, is there a place to do that?

You cannot download a Graphcool project. However, you can download the examples I linked in my previous post even after you changed your project models or relations. Follow the instructions found in the example repositories to connect the example to your project. We do some additional steps for you when you download one of the examples during the getting started tour that you have to do manually when downloading the example from Github.

> How can I inspect the schema code created with graph.cool as shown in this example in apollostack dev docs here?

I am not sure if I understand what you mean here. You cannot inspect the literal code that created your schema on Graphcool, however you can indeed inspect your actual schema in the Playground inside your Graphcool project. To see how to use the integrated GraphiQL instance, you can [watch this video](https://egghead.io/lessons/javascript-using-graphql-s-graphiql-tool).

**Comment by marktani** [comment]
> Since graph.cool is automatically generating the queries in the code why would I go into it and paste it?

You explore the available queries in the Playground and paste them to your client application.

Let me try to explain a workflow that has proven effective with the following scenario that explains how we added GraphQL queries to the [React and Apollo example](https://github.com/graphcool-examples/react-apollo-instagram-example/).

In this scenario, you already finished the following steps:
* You decided to build an "Instagram for Cats" app
* You added all the needed models and relations to your Graphcool project  
* You created a basic component hierarchy in React, but you have not included any GraphQL queries to it yet. One of your components is the [`ListPage` component](https://github.com/graphcool-examples/react-apollo-instagram-example/blob/master/src/components/ListPage.js) that should show a list of posts. 

Now you want to wrap the `ListPage` component with Apollo and query all posts to inject them with `this.props.data.allPosts`. But the question is, how does that query look like? At this stage, finally, the "copy & paste step" mentioned in the guide comes into play: you go with "I want to query all the posts" in mind to the Playground of your Graphcool project. Then you use the auto completion to work out this query
```graphql
query {
  allPosts {
    id
    imageUrl
    description
  }
}
``` 

Now you can copy & paste this query to your `ListPage` component. That is exactly what we can see in [`ListPage.js` of the example](https://github.com/graphcool-examples/react-apollo-instagram-example/blob/master/src/components/ListPage.js#L32).

I hope that this clears things up. Again, I will improve this specific paragraph in the coming days :)

**Comment by marktani** [comment]
Feel free to hit me up in Slack if you want to discuss more on this topic.
